"""add review

Revision ID: 01e0eb45947b
Revises: 3ca8f3813d09
Create Date: 2024-10-08 12:48:17.503590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e0eb45947b'
down_revision = '3ca8f3813d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('items', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('reviews', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('fk_reviews_customer_id_customers', 'reviews', type_='foreignkey')
    op.drop_constraint('fk_reviews_item_id_items', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_customer_id_customers'), 'reviews', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(op.f('fk_reviews_item_id_items'), 'reviews', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_item_id_items'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_customer_id_customers'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_item_id_items', 'reviews', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_reviews_customer_id_customers', 'reviews', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reviews', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('items', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
